[Variables]
;Currently selected theme
Theme=0
;What music player do you use?
;Options: WMP, iTunes, AIMP, CAD (works with foobar2000, Jriver media center, VLC, Musicbee and Media Jukebox), Winamp
MadiaPlayer=Spotify

fontName=Kode Mono
textSize=15
headerTextSize=9


;----------------------------------------------------
;Edit the themes here if you like!
;----------------------------------------------------

ThemeName=[#ThemeName[#Theme]]
BDColor=[#BDColor[#Theme]]
BGColor=[#BGColor[#Theme]]
NormalTextColor=[#NormalTextColor[#Theme]]
DictColor=[#DictColor[#Theme]]
VarNameColor=[#VarNameColor[#Theme]]
ParamNameColor=[#ParamNameColor[#Theme]]
DividerCharsColor=[#DividerCharsColor[#Theme]]
BracketsColor=[#BracketsColor[#Theme]]
HeaderColor=[#HeaderColor[#Theme]]


ThemeName0=DEFAULT
BDColor0=57,61,68
BGColor0=0,0,0,128
NormalTextColor0=118,235,7
DictColor0=AB36C2
VarNameColor0=14,216,241
ParamNameColor0=FD5050
DividerCharsColor0=FFFFFF
BracketsColor0=F4B620
HeaderColor0=240,240,240